apiVersion: v1
kind: Service
metadata:
  name: {{ include "xdc-node.fullname" . }}
  labels:
    {{- include "xdc-node.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.rpc.enabled }}
    - name: rpc
      port: {{ .Values.service.rpc.port }}
      targetPort: rpc
      protocol: TCP
    {{- end }}
    {{- if .Values.service.ws.enabled }}
    - name: ws
      port: {{ .Values.service.ws.port }}
      targetPort: ws
      protocol: TCP
    {{- end }}
    {{- if .Values.service.metrics.enabled }}
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "xdc-node.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.p2p.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xdc-node.fullname" . }}-p2p
  labels:
    {{- include "xdc-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.p2p.type }}
  ports:
    - name: p2p-tcp
      port: {{ .Values.xdc.p2pPort }}
      targetPort: p2p-tcp
      {{- if eq .Values.service.p2p.type "NodePort" }}
      nodePort: {{ .Values.service.p2p.nodePort }}
      {{- end }}
      protocol: TCP
    - name: p2p-udp
      port: {{ .Values.xdc.p2pPort }}
      targetPort: p2p-udp
      {{- if eq .Values.service.p2p.type "NodePort" }}
      nodePort: {{ .Values.service.p2p.nodePort }}
      {{- end }}
      protocol: UDP
  selector:
    {{- include "xdc-node.selectorLabels" . | nindent 4 }}
{{- end }}
