apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xdc-node-data
  namespace: xdc
  labels:
    app.kubernetes.io/name: xdc-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: standard
